//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EyeDiseaseRecognition.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Drawing;

	/// <remarks>
	/// Reprezentuje jedno badanie/katalog ze zdjęciami
	/// generuje dla badania dokument XML, który będzie przechowywał informacje o wyekstrahowanych cechach
	/// 
	/// </remarks>
	public class Examination
	{
		public virtual object ExaminationMetadata
		{
			get;
			set;
		}

		public virtual Image Image
		{
			get;
			set;
		}

	}
}

